### ISSUE TITLE
[Oaisys] Fix failing tests

### ISSUE THREAD

**Issue by ConnorSheremeta** [ualbertalib/jupiter#1817]
There are two failing tests for oaisys in jupiter below:

```
E

Error:
OaisysListSetsTest#test_test_list_sets_resumption_token_xml:
ActionController::RoutingError: No route matches [GET] "/oai/oai"
    test/integration/oaisys_list_sets_test.rb:47:in `block in <class:OaisysListSetsTest>'


rails test test/integration/oaisys_list_sets_test.rb:12

...E

Error:
OaisysListIdentifiersTest#test_list_identifers_items_xml:
ActionController::RoutingError: No route matches [GET] "/oai/oai"
    test/integration/oaisys_list_identifiers_test.rb:48:in `block in <class:OaisysListIdentifiersTest>'


rails test test/integration/oaisys_list_identifiers_test.rb:18

```

as soon as  [match '/oai/(*all)', to: 'application#service_unavailable', via: [:get, :post]](https://github.com/ualbertalib/jupiter/blob/b512a9084867acdda3292a6377f255395d817467/config/routes.rb#L121) is removed (which is required for it to work) the tests fail.

**Comment by ConnorSheremeta** [comment]
This has been found to be a rails bug and has been submitted here https://github.com/rails/rails/issues/40078

Will skip the tests for now
