### ISSUE TITLE
[Oaisys] Resolve added parameter

### ISSUE THREAD

**Issue by ConnorSheremeta** [ualbertalib/jupiter#1824]
There is a parameter being added somewhere `("pmh"=>{}`) that is causing dev to not work (action on unpermitted params is raise on dev) and also causes oaisys to think there is an extra argument that is illegal. This has been patched over here **#1816** to ignore the parameter but we need to find out what put it there in the first place. This seems to be a little sporadic as it doesn't always occur.

ActionController::UnpermittedParameters at /
============================================

> found unpermitted parameter: :pmh

actionpack (6.0.3.2) lib/action_controller/metal/strong_parameters.rb, line 885
-------------------------------------------------------------------------------

``` ruby
  880             case self.class.action_on_unpermitted_parameters
  881             when :log
  882               name = "unpermitted_parameters.action_controller"
  883               ActiveSupport::Notifications.instrument(name, keys: unpermitted_keys)
  884             when :raise
> 885               raise ActionController::UnpermittedParameters.new(unpermitted_keys)
  886             end
  887           end
  888         end
  889   
  890         def unpermitted_keys(params)
```

App backtrace
-------------

Full backtrace
--------------

 - actionpack (6.0.3.2) lib/action_controller/metal/strong_parameters.rb:885:in `unpermitted_parameters!'
 - actionpack (6.0.3.2) lib/action_controller/metal/strong_parameters.rb:559:in `permit'
 - /home/connor/oaisys/app/controllers/oaisys/pmh_controller.rb:193:in `expect_args'
 - /home/connor/oaisys/app/controllers/oaisys/pmh_controller.rb:75:in `list_records'

**Comment by ConnorSheremeta** [comment]
This may of been resolved in https://github.com/ualbertalib/jupiter/issues/1808? Either that or I am having troubles experiencing it again.

**Comment by ConnorSheremeta** [comment]
I could not reproduce this either so I think it's safe to close it!
