### ISSUE TITLE
Occasional Test Suite failures

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#2129]
**Describe the bug**
Occasionally CI will catch failing tests like the following:

1. 
```
Failure:
DoiResetTest#test_reset_button_displays_as_needed [/home/runner/work/jupiter/jupiter/test/integration/doi_reset_test.rb:19]:
Expected exactly 0 elements matching ".admin-sidebar .btn", found 1..
Expected: 0
  Actual: 1
```
rails test test/integration/doi_reset_test.rb:12
**To Reproduce**
Run options: --seed 41156

**Expected behavior**
Stable and consistent test suite.

**Additional context**
There are others I've seen recently.  I'll update as I experience them.

**Comment by pgwillia** [comment]
`rails system:test ` on WSL2 (so might just be my machine 😅 )

```
Failure:
AdminUsersShowTest#test_should_be_able_to_login_as_a_regular_user [/mnt/c/Users/pgwillia/Code/ualbertalib/jupiter/test/system/admin_users_show_test.rb:116]:
expected to find visible css "h1" with text "Dashboard" but there were no matches. Also found "ERA:\nEducation and Research Archive", which matched the selector but not all filters.


rails test test/system/admin_users_show_test.rb:107
```

```
Error:
EditItemOldLicenseTest#test_can_edit_and_save_an_item_with_an_old_license:
Capybara::ElementNotFound: Unable to find link or button "Save and continue to next step"
    test/system/edit_item_old_license_test.rb:21:in `block in <class:EditItemOldLicenseTest>'


rails test test/system/edit_item_old_license_test.rb:5
```

```
Failure:
AdminUsersIndexTest#test_should_be_able_to_sort_columns [/mnt/c/Users/pgwillia/Code/ualbertalib/jupiter/test/system/admin_users_index_test.rb:25]:
expected to find visible css "tbody tr:last-child th[scope=\"row\"]" with text "administrator@example.com" but there were no matches. Also found "tyrion_lannister@example.com", which matched the selector but not all filters.


rails test test/system/admin_users_index_test.rb:5
```

![failures_test_should_be_able_to_sort_columns](https://user-images.githubusercontent.com/1220762/113048058-5772e400-915f-11eb-9459-00a670bf79e7.png)
![failures_test_can_edit_and_save_an_item_with_an_old_license](https://user-images.githubusercontent.com/1220762/113048061-580b7a80-915f-11eb-8e58-cc646e6ede12.png)

**Comment by pgwillia** [comment]
```
Failure:
AdminUsersIndexTest#test_should_be_able_to_autocomplete_by_name [/home/runner/work/jupiter/jupiter/test/system/admin_users_index_test.rb:56]:
expected to find visible css "tbody tr" 1 time, found 6 matches: "administrator@example.com Administrator 2021-04-23 less than a minute ago Admin Active", "tyrion_lannister@example.com Tyrion Lannister 2021-04-23 Never Signed In Admin Active", "john_snow@example.com John Snow 2021-04-23 Never Signed In User Active", "daenerys_targaryen@example.com Daenerys Targaryen 2021-04-23 Never Signed In User Active", "joffrey_baratheon@example.com Joffrey Baratheon 2021-04-23 Never Signed In User Suspended", "ditech@ualberta.ca System user 2021-04-23 Never Signed In User Active"

rails test test/system/admin_users_index_test.rb:46
```

**Comment by pgwillia** [comment]
Failure:
DepositThesisTest#test_be_able_to_deposit_and_edit_a_thesis_successfully [/home/runner/work/jupiter/jupiter/test/system/deposit_thesis_test.rb:62]:
expected to find visible css "h2" with text "Review and Deposit Thesis" but there were no matches. Also found "Upload Files", which matched the selector but not all filters. 

rails test test/system/deposit_thesis_test.rb:5

--seed 26145

**Comment by pgwillia** [comment]
```
Error:
AdminUsersIndexTest#test_should_be_able_to_filter_by_status:
Capybara::ElementNotFound: Unable to find link "Users"
    test/system/admin_users_index_test.rb:69:in `block in <class:AdminUsersIndexTest>'

rails test test/system/admin_users_index_test.rb:62
```
--seed 5723

**Comment by pgwillia** [comment]
```
Failure:
DepositItemTest#test_be_able_to_deposit_and_edit_an_item_successfully [/home/runner/work/jupiter/jupiter/test/system/deposit_item_test.rb:65]:
expected to find visible css "h2" with text "Review and Deposit Item" but there were no matches. Also found "Upload Files", which matched the selector but not all filters. 

rails test test/system/deposit_item_test.rb:5
```

--seed 4532

**Comment by pgwillia** [comment]
```
Error:
DepositItemTest#test_be_able_to_deposit_and_edit_an_item_successfully:
Selenium::WebDriver::Error::StaleElementReferenceError: stale element reference: element is not attached to the page document
  (Session info: headless chrome=92.0.4515.131)
    test/system/deposit_item_test.rb:142:in `block in selectize_set_text'
    test/system/deposit_item_test.rb:140:in `selectize_set_text'
    test/system/deposit_item_test.rb:25:in `block in <class:DepositItemTest>'

rails test test/system/deposit_item_test.rb:5
```
