### ISSUE TITLE
Preserving the backlog of items created in the last year

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#2566]
- [x] @pgwillia is going to investigate if there is a queue for pmpy ready to go or how the back log will be resolved.

Kenton was asking if once we release our pushmi_pullyu fix if the workflow will just work again or if there is anything we have to do to get it to preserve the backlog?  I'm going to take a look at what is currently in the production queue, and if the format is correct.  I'll also check how we might kick off proper jobs for anything that hasn't been preserved if that turns out to be the case.

_Originally posted by @pgwillia in https://github.com/ualbertalib/jupiter/issues/2524#issuecomment-945970088_

**Comment by pgwillia** [comment]
The queue will have just the ids on it
![image](https://user-images.githubusercontent.com/1220762/138167913-c9c3bcab-a6a1-4c3b-83d3-ea4fee64d87f.png)
Which is the cause for our issues with pushmi_pullyu
```
$ pushmi_pullyu
Loading PushmiPullyu 2.0.1
Running in ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux]
Starting processing, hit Ctrl-C to stop
Traceback (most recent call last):
        8: from /home/pjenkins/.asdf/installs/ruby/2.7.4/bin/pushmi_pullyu:23:in `<main>'
        7: from /home/pjenkins/.asdf/installs/ruby/2.7.4/bin/pushmi_pullyu:23:in `load'
        6: from /home/pjenkins/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/pushmi_pullyu-2.0.1/exe/pushmi_pullyu:7:in `<top (required)>'
        5: from /home/pjenkins/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/cli.rb:38:in `run'
        4: from /home/pjenkins/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/cli.rb:54:in `start_server'
        3: from /home/pjenkins/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/cli.rb:214:in `run_tick_loop'
        2: from /home/pjenkins/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/pushmi_pullyu-2.0.1/lib/pushmi_pullyu/cli.rb:185:in `run_preservation_cycle'
        1: from /home/pjenkins/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/json-2.6.0/lib/json/common.rb:216:in `parse'
/home/pjenkins/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/json-2.6.0/lib/json/common.rb:216:in `parse': 859: unexpected token at 'b4b61a-bdc0-4e27-9970-e754b789615c' (JSON::ParserError)
```
The reason for this is because pushmi_pullyu is expecting both the `type` and `uuid`
https://github.com/ualbertalib/pushmi_pullyu/blob/c0bccd20ed049afa3d26de0b9896f87855a053c2/lib/pushmi_pullyu/cli.rb#L184-L190
Which would look like this (from our master branch)
![image](https://user-images.githubusercontent.com/1220762/138169367-9757dc6d-88dd-4e07-959d-51aa657f7e6e.png)

Each time pushmi_pullyu is started and fails the top item is removed from the queue.  We cannot use the existing queue to reliably clear the backlog.  In fact we must ensure it is empty before we start pushmi_pullyu.

**Comment by pgwillia** [comment]
If we didn't want to push all items, we could use an existing scope:
`Item.updated_on_or_after(DATE_THAT_PRESERVATION_STOPPED_WORKING).each {|item| item.push_entity_for_preservation}`

**Comment by pgwillia** [comment]
Confirmed to work with era-test
