### ISSUE TITLE
Re-index fails in staging due to missing sdoc 

### ISSUE THREAD

**Issue by lagoan** [ualbertalib/jupiter#3140]
**Describe the bug**
Trying to re-index the staging instance of jupiter fails with the following error:

```
[root@era-app-stg-1 jupiter]# rake jupiter:reindex
rake aborted!
LoadError: cannot load such file -- sdoc
/var/www/sites/jupiter/vendor/ruby/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/var/www/sites/jupiter/vendor/ruby/3.1.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
/var/www/sites/jupiter/vendor/ruby/3.1.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
/var/www/sites/jupiter/vendor/ruby/3.1.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies.rb:332:in `block in require'
/var/www/sites/jupiter/vendor/ruby/3.1.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/www/sites/jupiter/vendor/ruby/3.1.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies.rb:332:in `require'
/var/www/sites/jupiter/lib/tasks/rdoc.rake:3:in `<main>'
/var/www/sites/jupiter/vendor/ruby/3.1.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies.rb:326:in `load'
/var/www/sites/jupiter/vendor/ruby/3.1.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies.rb:326:in `block in load'
/var/www/sites/jupiter/vendor/ruby/3.1.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/www/sites/jupiter/vendor/ruby/3.1.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies.rb:326:in `load'
/var/www/sites/jupiter/vendor/ruby/3.1.0/gems/railties-6.1.7.2/lib/rails/engine.rb:675:in `block in run_tasks_blocks'
/var/www/sites/jupiter/vendor/ruby/3.1.0/gems/railties-6.1.7.2/lib/rails/engine.rb:675:in `each'
/var/www/sites/jupiter/vendor/ruby/3.1.0/gems/railties-6.1.7.2/lib/rails/engine.rb:675:in `run_tasks_blocks'
/var/www/sites/jupiter/vendor/ruby/3.1.0/gems/railties-6.1.7.2/lib/rails/application.rb:528:in `run_tasks_blocks'
/var/www/sites/jupiter/vendor/ruby/3.1.0/gems/railties-6.1.7.2/lib/rails/engine.rb:464:in `load_tasks'
/var/www/sites/jupiter/Rakefile:6:in `<top (required)>'
(See full trace by running task with --trace)
```

**To Reproduce**
1. Login to staging server
2. In console run ```rake jupiter:reindex```

**Expected behavior**
The rake task should run successfully

**Additional context**
The index needs to be regenerated after a feature flag was turned on to allow for OR faceting.

**Comment by lagoan** [comment]
I was able to run the re-index rake task with:

```
sudo su apache -s /bin/bash
cd /var/www/sites/jupiter/
RAILS_ENV=staging rake jupiter:reindex
```

My computer got disconnected and could not complete the process.

@beausapach let us know how the new attempt goes.
