### ISSUE TITLE
Dockerfile.deployment needs some updates

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#3268]
**Describe the bug**
Failing in [Docker Hub](https://hub.docker.com/repository/registry-1.docker.io/ualbertalib/jupiter/builds/5dadf316-f813-468a-b87c-33012b57bcd6) builds

**To Reproduce**
https://hub.docker.com/repository/registry-1.docker.io/ualbertalib/jupiter/builds

But also in a terminal following instructions [here](https://github.com/ualbertalib/di_internal/blob/master/System-Administration/UAT/UAT-Environment.md#deploy-without-dockerhubs-autobuilt)
```
$ docker build -f Dockerfile.deployment -t ualbertalib/jupiter:deployment  .
[+] Building 225.7s (16/16) FINISHED                                                                                                                                                         docker:default
 => [internal] load build definition from Dockerfile.deployment                                                                                                                                        0.0s
 => => transferring dockerfile: 2.14kB                                                                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                                                                      0.0s
 => => transferring context: 239B                                                                                                                                                                      0.0s
 => [internal] load metadata for docker.io/library/ruby:3.1                                                                                                                                            0.9s
 => [ 1/12] FROM docker.io/library/ruby:3.1@sha256:f79e08b89a622210d611eab0737ad4599d7aa74a019a2f76b0a9438f19094611                                                                                   72.6s
 => => resolve docker.io/library/ruby:3.1@sha256:f79e08b89a622210d611eab0737ad4599d7aa74a019a2f76b0a9438f19094611                                                                                      0.0s
 => => sha256:0a9573503463fd3166b5b1f34a7720dac28609e98d731e50e7068f92e79b8545 49.58MB / 49.58MB                                                                                                      36.2s
 => => sha256:1ccc26d841b4acc2562483bf393ce1cf8bc358ced09ccd825425226827c79c92 24.05MB / 24.05MB                                                                                                      22.7s
 => => sha256:f79e08b89a622210d611eab0737ad4599d7aa74a019a2f76b0a9438f19094611 1.86kB / 1.86kB                                                                                                         0.0s
 => => sha256:1071c7e93914582ffc858691072157b681d5f59808059937aff0f7a34366c701 7.02kB / 7.02kB                                                                                                         0.0s
 => => sha256:800d84653581fc119cd75cd572fa190d3b813d49221b9e5ee463e3560e2cb342 64.13MB / 64.13MB                                                                                                      24.1s
 => => sha256:d3aa2c41ae22575fdf8df9c3b27c294d80f5e0685f0c2dae09eef005e9150ae0 1.79kB / 1.79kB                                                                                                         0.0s
 => => sha256:7c632e57ea62ea950c367f484f52cdcfd2adb12060a31f5c413f40db9822e96e 211.06MB / 211.06MB                                                                                                    69.0s
 => => sha256:3469b85d26eff88b11203f3dc91dc808bc923ebbc3a86a11ac3093bd39d8edb7 199B / 199B                                                                                                            24.2s
 => => sha256:98b0161614afbddd4750b1ca8272eb3c3cbd51301d09629f5f0624666119df80 32.78MB / 32.78MB                                                                                                      35.9s
 => => sha256:5dc40b1a1fd9e2c3d112b6a4e68d020c4e1fca6ea22f135283de1c1a1efb1a89 177B / 177B                                                                                                            36.2s
 => => extracting sha256:0a9573503463fd3166b5b1f34a7720dac28609e98d731e50e7068f92e79b8545                                                                                                              0.8s
 => => extracting sha256:1ccc26d841b4acc2562483bf393ce1cf8bc358ced09ccd825425226827c79c92                                                                                                              0.3s
 => => extracting sha256:800d84653581fc119cd75cd572fa190d3b813d49221b9e5ee463e3560e2cb342                                                                                                              1.1s
 => => extracting sha256:7c632e57ea62ea950c367f484f52cdcfd2adb12060a31f5c413f40db9822e96e                                                                                                              3.0s
 => => extracting sha256:3469b85d26eff88b11203f3dc91dc808bc923ebbc3a86a11ac3093bd39d8edb7                                                                                                              0.0s
 => => extracting sha256:98b0161614afbddd4750b1ca8272eb3c3cbd51301d09629f5f0624666119df80                                                                                                              0.4s
 => => extracting sha256:5dc40b1a1fd9e2c3d112b6a4e68d020c4e1fca6ea22f135283de1c1a1efb1a89                                                                                                              0.0s
 => [internal] load build context                                                                                                                                                                      0.6s
 => => transferring context: 3.27MB                                                                                                                                                                    0.6s
 => [ 2/12] RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -                                                                                                                               66.8s
 => [ 3/12] RUN curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | tee /usr/share/keyrings/yarnkey.gpg >/dev/null     && echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https  1.2s
 => [ 4/12] RUN apt-get update -qq     && apt-get install -y build-essential                           libpq-dev                           nodejs                           yarn                      10.9s 
 => [ 5/12] RUN mkdir -p /app                                                                                                                                                                          0.4s 
 => [ 6/12] WORKDIR /app                                                                                                                                                                               0.0s 
 => [ 7/12] RUN gem update --system                                                                                                                                                                    4.6s 
 => [ 8/12] RUN gem install bundler:2.1.4                                                                                                                                                              1.0s 
 => [ 9/12] COPY Gemfile* /app/                                                                                                                                                                        0.1s 
 => [10/12] RUN bundle config --global frozen 1 &&     bundle install -j4 --retry 3                                                                                                                   45.9s 
 => [11/12] COPY . /app                                                                                                                                                                                1.8s
 => ERROR [12/12] RUN RAILS_ENV=uat DATABASE_URL=postgresql://user:pass@127.0.0.1/dbname SECRET_KEY_BASE=pickasecuretoken bundle exec rake assets:precompile                                          19.6s
```

It looks like the problem is with the `rake assets:precompile` step

```
Compiling...
19.23 Compilation failed:
19.23 Browserslist: caniuse-lite is outdated. Please run:
19.23   npx browserslist@latest --update-db
19.23   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
19.23 node:internal/crypto/hash:71
19.23   this[kHandle] = new _Hash(algorithm, xofLen);
19.23                   ^
19.23 
19.23 Error: error:0308010C:digital envelope routines::unsupported
19.23     at new Hash (node:internal/crypto/hash:71:19)
19.23     at Object.createHash (node:crypto:133:10)
19.23     at module.exports (/app/node_modules/webpack/lib/util/createHash.js:135:53)
19.23     at NormalModule._initBuildHash (/app/node_modules/webpack/lib/NormalModule.js:417:16)
19.23     at /app/node_modules/webpack/lib/NormalModule.js:452:10
19.23     at /app/node_modules/webpack/lib/NormalModule.js:323:13
19.23     at /app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
19.23     at /app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
19.23     at context.callback (/app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
19.23     at /app/node_modules/babel-loader/lib/index.js:59:103 {
19.23   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
19.23   library: 'digital envelope routines',
19.23   reason: 'unsupported',
19.23   code: 'ERR_OSSL_EVP_UNSUPPORTED'
19.23 }
19.23 
19.23 Node.js v18.13.0

```

**Expected behavior**
We're maintaining this, and fixing it when it doesn't work.

`docker build -f Dockerfile.deployment -t ualbertalib/jupiter:deployment  .` is successful

https://hub.docker.com/repository/registry-1.docker.io/ualbertalib/jupiter/builds for latest and deployment are successful.

**Additional context**
https://github.com/ualbertalib/jupiter/pull/3264

**Comment by pgwillia** [comment]
![image](https://github.com/ualbertalib/jupiter/assets/1220762/01e52987-f552-4a80-a589-7b061e40a89c)

Looks to be working now after replacing webpacker!
