### ISSUE TITLE
CI test failure

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#3585]
**Describe the bug**
In this run there were two test errors https://github.com/ualbertalib/jupiter/actions/runs/11349363028/job/31565282695
```
Error:
PageLayoutHelperTest#test_page_image_url_should_return_community/item_logo:
TypeError: no implicit conversion of nil into String
    test/helpers/page_layout_helper_test.rb:94:in `+'
    test/helpers/page_layout_helper_test.rb:94:in `block in <class:PageLayoutHelperTest>'

bin/rails test test/helpers/page_layout_helper_test.rb:88
```
```
Error:
PageLayoutHelperTest#test_thumbnail_path_should_return_preview_for_image_(Variable):
MiniMagick::Error: You must have ImageMagick or GraphicsMagick installed
    test/helpers/page_layout_helper_test.rb:126:in `block in <class:PageLayoutHelperTest>'

bin/rails test test/helpers/page_layout_helper_test.rb:118
```

Looks like ImageMagick or GraphicsMagick dependency is not available.

**Expected behavior**
Tests pass in CI

**Comment by pgwillia** [comment]
https://github.blog/changelog/2024-09-25-end-of-life-for-actions-node16/ October 15th matches timing.

**Comment by pgwillia** [comment]
Crisis averted?  Depedabot PRs starting Oct 16 at 10 am seem to be [fine](https://github.com/ualbertalib/jupiter/pull/3591).
