### ISSUE TITLE
Handle failure to load thumbnail images better

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/jupiter#904]
During a recent test of unmount era_assets (the intermediate access storage, where the thumbnail images and the access copy of the objects are stored), we notice that item view page, search page, and collection view page fails because of the rendering of the thumbnail images (stack trace below)

We will need a better way to handle thumbnails so when they are failed to load, they don't bring down the majority of the application's function. 

```
F, [2018-10-31T10:18:17.401245 #1717] FATAL -- : [9caacbe2-00d0-41e0-90fe-4a5597703169]   
F, [2018-10-31T10:18:17.401276 #1717] FATAL -- : [9caacbe2-00d0-41e0-90fe-4a5597703169] ActionView::Template::Error (No such file or directory @ rb_sysopen - /era_assets/9z/9i/9z9iki8V4cksKvex6zCFWvxd):
F, [2018-10-31T10:18:17.401338 #1717] FATAL -- : [9caacbe2-00d0-41e0-90fe-4a5597703169]     1: <% if policy(object).thumbnail? %>
[9caacbe2-00d0-41e0-90fe-4a5597703169]     2:   <% if object.thumbnail_url.present? %>
[9caacbe2-00d0-41e0-90fe-4a5597703169]     3:     <%= image_tag(object.thumbnail_url, class: 'j-thumbnail img-thumbnail', alt: '', title: object.title, size: '100x100') %>
[9caacbe2-00d0-41e0-90fe-4a5597703169]     4:   <% else %>
[9caacbe2-00d0-41e0-90fe-4a5597703169]     5:     <% if object.is_a? Community %>
F, [2018-10-31T10:18:17.401357 #1717] FATAL -- : [9caacbe2-00d0-41e0-90fe-4a5597703169]   
F, [2018-10-31T10:18:17.401379 #1717] FATAL -- : [9caacbe2-00d0-41e0-90fe-4a5597703169] app/models/concerns/item_properties.rb:69:in `rescue in thumbnail_url'
[9caacbe2-00d0-41e0-90fe-4a5597703169] app/models/concerns/item_properties.rb:63:in `thumbnail_url'
[9caacbe2-00d0-41e0-90fe-4a5597703169] app/views/application/_thumbnail.html.erb:2:in `_app_views_application__thumbnail_html_erb___3120241352277171330_69786600'
[9caacbe2-00d0-41e0-90fe-4a5597703169] app/views/application/_item.html.erb:4:in `block in _app_views_application__item_html_erb___24428983217641877_73436520'
[9caacbe2-00d0-41e0-90fe-4a5597703169] app/views/application/_item.html.erb:3:in `_app_views_application__item_html_erb___24428983217641877_73436520'
[9caacbe2-00d0-41e0-90fe-4a5597703169] app/views/application/_results.html.erb:85:in `block in _app_views_application__results_html_erb___1048356341912818400_49778500'
[9caacbe2-00d0-41e0-90fe-4a5597703169] app/models/jupiter_core/deferred_faceted_solr_query.rb:90:in `block in each'
[9caacbe2-00d0-41e0-90fe-4a5597703169] app/models/jupiter_core/deferred_faceted_solr_query.rb:88:in `map'
[9caacbe2-00d0-41e0-90fe-4a5597703169] app/models/jupiter_core/deferred_faceted_solr_query.rb:88:in `each'
[9caacbe2-00d0-41e0-90fe-4a5597703169] app/views/application/_results.html.erb:83:in `_app_views_application__results_html_erb___1048356341912818400_49778500'
[9caacbe2-00d0-41e0-90fe-4a5597703169] app/views/collections/show.html.erb:61:in `_app_views_collections_show_html_erb___159708252536820503_51478220'
```

**Comment by weiweishi** [comment]
Will try to serve the files through Apache based on spike #156
