### ISSUE TITLE
Investigate Flapping Tests

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/jupiter#999]
**Describe the bug**
Occasionally we'll see some tests on Travis fail.  We suspect that they are javascript or sort order related. We've added logic to skip the known flapping tests on Travis.  They will still run locally where they seem to pass without issue.

**To Reproduce**
Created a `flapping_test` branch.  This is [scheduled](https://travis-ci.org/ualbertalib/jupiter/settings) to run on travis daily so that we have a history of the [failures](https://travis-ci.org/ualbertalib/jupiter/builds/484561042).

**Expected behavior**
Tests should be green on all test environments.

**Additional context**
Previously investigation https://github.com/ualbertalib/jupiter/issues/811

**Comment by pgwillia** [comment]
Here's a ?new? example

```
$ bundle exec rails test:system
Run options: --seed 1933
# Running:
SSCapybara starting Puma...
* Version 3.12.0 , codename: Llamas in Pajamas
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:38021
...........S....S..........[Screenshot]: tmp/screenshots/failures_test_anybody_should_be_able_to_sort_results.png
F
Failure:
SearchTest#test_anybody_should_be_able_to_sort_results [/home/travis/build/ualbertalib/jupiter/test/system/search_test.rb:250]:
Expected /Fancy Item 0.*Fancy Item 2.*Fancy Item 4.*Fancy Item 6.*Fancy Item 8/m to match "Skip to Main Content\nSearch\nCollections\nDeposit\nAbout\nLog In\nThis is a test message!\nSearch\nItems (5)\nCollections\nCommunities\nSkip to Search Results\nFilter\nAuthor / Creator / Contributor\n5\nJoe Blow\nSubject / Keyword\n3\nItems\nYear\nto\nCollections\n5\nFancy Community\n3\nFancy Community/Fancy Collection 0\n2\nFancy Community/Fancy Collection 1\nLanguages\n5\nEnglish\nItem type\n3\nArticle (Published)\n2\nThesis\nResults for \"Fancy\"\nSort by\nFancy Item 0\nFancy Item 0\n1950-11-11\nJoe Blow\nFancy Item 2\nFancy Item 2\n1952-11-11\nJoe Blow\nFancy Item 4\nFancy Item 4\n1954-11-11\nJoe Blow\nFancy Item 8\nFancy Item 8\n1958-11-11\nJoe Blow\nFancy Item 6\nFancy Item 6\n1956-11-11\nJoe Blow\n1 - 5 of 5\nAbout ERA · Contact Us · Policies · Powered by Jupiter".
bin/rails test test/system/search_test.rb:242
```

**Comment by pgwillia** [comment]
And another https://travis-ci.org/ualbertalib/jupiter/builds/493959307?utm_source=github_status&utm_medium=notification

```
$ bundle exec rails test:system
Run options: --seed 21157
# Running:
Capybara starting Puma...
* Version 3.12.0 , codename: Llamas in Pajamas
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:46227
..S[Screenshot]: tmp/screenshots/failures_test_should_populate_community_and_collection_when_coming_from_a_restricted_collection_page.png
E
Error:
DepositThesisTest#test_should_populate_community_and_collection_when_coming_from_a_restricted_collection_page:
Capybara::ElementNotFound: Unable to find link "Theses Collection"
    test/system/deposit_thesis_test.rb:109:in `block in <class:DepositThesisTest>'
bin/rails test test/system/deposit_thesis_test.rb:101
```

**Comment by pgwillia** [comment]
I think the problem is that the test message is in the place of another that's expected.  Need to track down which test is leaving that in.

```
Run options: --seed 9452

# Running:

Capybara starting Puma...
* Version 3.12.0 , codename: Llamas in Pajamas
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:42295
......[Screenshot]: tmp/screenshots/failures_test_can_edit_item.png
F


Failure:
ItemEditTest#test_can_edit_item [/home/pjenkins/Code/jupiter/test/system/item_edit_test.rb:55]:
expected to find text "Item Deposit was successful!" in "Skip to Main Content\nSearch\nCollections\nDeposit\nAbout\nJohn Snow\nThis is a test message!\nEdit Item\nStep 1
\nDescribe Item\nStep 2\nChoose License and Visibility\nStep 3\nUpload Files\nStep 4\nReview and Deposit Item\nStep 4 of 4\nReview and Update Item\nPlease review your it
em before depositing into ERA\nEdit\nUpload Files\nera-logo.png\n4.28 KB\nEdit\nChoose License and Visibility\nLicense\nAttribution 4.0 International (CC BY 4.0)\nVisibi
lity\nOpen access (will be seen by everyone)\nEdit\nDescribe Item\nTitle\nBook of Random\nType of Item\nBook\nLanguages\nEnglish\nAuthors/Creators\nJane Doe\nBob Smith\n
Subjects/Keywords\nBest Seller\nAdventure\nDate created\n2018-10-24\nDescription or Abstract\nReally random description about this random book\nCommunity and Collection\
nFancy Community / Fancy collection\nBy depositing this item into ERA you agree to the ERA Deposit Policy agreements\nPrevious step\nSave\nAbout ERA · Contact Us · Polic
ies · Powered by Jupiter"


bin/rails test test/system/item_edit_test.rb:5

[Screenshot]: tmp/screenshots/failures_test_should_populate_community_and_collection_when_coming_from_collection_page.png
E

Error:
DepositItemTest#test_should_populate_community_and_collection_when_coming_from_collection_page:
Capybara::ElementNotFound: Unable to find link or button "Log In"
    test/application_system_test_case.rb:26:in `login_user'
    test/system/deposit_item_test.rb:106:in `block in <class:DepositItemTest>'


bin/rails test test/system/deposit_item_test.rb:103

.............................

Finished in 123.697192s, 0.2991 runs/s, 3.4439 assertions/s.
37 runs, 426 assertions, 1 failures, 1 errors, 0 skips
Coverage report generated for MiniTest, Unit Tests to /home/pjenkins/Code/jupiter/coverage. 2296 / 2746 LOC (83.61%) covered.
```
![failures_test_should_populate_community_and_collection_when_coming_from_collection_page](https://user-images.githubusercontent.com/1220762/53604546-03f1ce80-3b72-11e9-8f9f-717664aa809b.png)
![failures_test_can_edit_item](https://user-images.githubusercontent.com/1220762/53604548-03f1ce80-3b72-11e9-8f81-d0d6ba041ba1.png)

**Comment by pgwillia** [comment]
https://travis-ci.org/ualbertalib/jupiter/builds/500265333?utm_source=github_status&utm_medium=notification
```
$ bundle exec rails test:system
Run options: --seed 40674
# Running:
Capybara starting Puma...
* Version 3.12.0 , codename: Llamas in Pajamas
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:45693
[Screenshot]: tmp/screenshots/failures_test_anybody_should_only_see_some_facet_results_by_default,_with_a_"show_more"_button.png
F
Failure:
SearchTest#test_anybody_should_only_see_some_facet_results_by_default,_with_a_"show_more"_button [/home/travis/build/ualbertalib/jupiter/test/system/search_test.rb:231]:
expected to find visible css "li a" with text /Extra Community/ 10 times, found 8 matches: "1\nExtra Community 5", "1\nExtra Community 5/Extra Collection 5", "1\nExtra Community 8", "1\nExtra Community 8/Extra Collection 8", "1\nExtra Community 0", "1\nExtra Community 0/Extra Collection 0", "1\nExtra Community 7", "1\nExtra Community 7/Extra Collection 7". Also found "Collections", "Deposit", "About", "Log In", "Items (10)", "Collections", "Communities", "10\nJoe Blow", "10\nItems", "1\nExtra Community 4", "1\nExtra Community 4/Extra Collection 4", "10\nEnglish", "10\nArticle (Published)", "Extra Item 0", "Extra Item 0", "Joe Blow", "Extra Item 1", "Extra Item 1", "Joe Blow", "Extra Item 2", "Extra Item 2", "Joe Blow", "Extra Item 3", "Extra Item 3", "Joe Blow", "Extra Item 4", "Extra Item 4", "Joe Blow", "Extra Item 5", "Extra Item 5", "Joe Blow", "Extra Item 6", "Extra Item 6", "Joe Blow", "Extra Item 7", "Extra Item 7", "Joe Blow", "Extra Item 8", "Extra Item 8", "Joe Blow", "Extra Item 9", "Extra Item 9", "Joe Blow", "About ERA", "Contact Us", "Policies", "Powered by Jupiter", which matched the selector but not all filters. 
bin/rails test test/system/search_test.rb:214
..........SS..............S.......S.
Finished in 142.800436s, 0.2591 runs/s, 2.1078 assertions/s.
37 runs, 301 assertions, 1 failures, 0 errors, 4 skips
```

**Comment by pgwillia** [comment]
> ```
SearchTest#test_anybody_should_only_see_some_facet_results_by_default,_with_a_"show_more"_button [/home/travis/build/ualbertalib/jupiter/test/system/search_test.rb:231]:
> expected to find visible css "li a" with text /Extra Community/ 10 times, found 8 matches: "1\nExtra Community 5", "1\nExtra Community 5/Extra Collection 5", "1\nExtra Community 8", "1\nExtra Community 8/Extra Collection 8", "1\nExtra Community 0", "1\nExtra Community 0/Extra Collection 0", "1\nExtra Community 7", "1\nExtra Community 7/Extra Collection 7". Also found "Collections", "Deposit", "About", "Log In", "Items (10)", "Collections", "Communities", "10\nJoe Blow", "10\nItems", "1\nExtra Community 4", "1\nExtra Community 4/Extra Collection 4", "10\nEnglish", "10\nArticle (Published)", "Extra Item 0", "Extra Item 0", "Joe Blow", "Extra Item 1", "Extra Item 1", "Joe Blow", "Extra Item 2", "Extra Item 2", "Joe Blow", "Extra Item 3", "Extra Item 3", "Joe Blow", "Extra Item 4", "Extra Item 4", "Joe Blow", "Extra Item 5", "Extra Item 5", "Joe Blow", "Extra Item 6", "Extra Item 6", "Joe Blow", "Extra Item 7", "Extra Item 7", "Joe Blow", "Extra Item 8", "Extra Item 8", "Joe Blow", "Extra Item 9", "Extra Item 9", "Joe Blow", "About ERA", "Contact Us", "Policies", "Powered by Jupiter", which matched the selector but not all filters. 
> bin/rails test test/system/search_test.rb:214
> ..........SS..............S.......S.
> Finished in 142.800436s, 0.2591 runs/s, 2.1078 assertions/s.
> 37 runs, 301 assertions, 1 failures, 0 errors, 4 skips
> ```
Happened again this morning.

**Comment by ConnorSheremeta** [comment]
Found another:
https://travis-ci.org/ualbertalib/jupiter/builds/548440788
```
Failure:
CommunitiesPaginationAndSortTest#test_anybody_should_be_able_to_sort_and_paginate_communities [/home/travis/build/ualbertalib/jupiter/test/system/communities_pagination_and_sort_test.rb:100]:
expected to find visible css "div" with text "11 - 11 of 11" but there were no matches. Also found "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", which matched the selector but not all filters. 
bin/rails test test/system/communities_pagination_and_sort_test.rb:15
```

Would it be appropriate to open a ticket to have travis skip the 6 flapping tests above and then another ticket to resolve them?

**Comment by pgwillia** [comment]
> Would it be appropriate to open a ticket to have travis skip the 6 flapping tests above and then another ticket to resolve them?

Yes!  Please.

**Comment by ConnorSheremeta** [comment]
Found another: 
F
Failure:
SearchTest#test_admin_should_be_able_to_filter_the_public_and_private_items [/home/travis/build/ualbertalib/jupiter/test/system/search_test.rb:363]:
expected to find css "a" but there were no matches
bin/rails test test/system/search_test.rb:324

Added issue to skip this test

**Comment by mbarnett** [comment]
This should all be fixed (I hope) with Shane's work, and if we run into new ones let's open a new ticket about it
